apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-configmap_01-complex.workflow2-resources.yaml
  - 01-sonataflow_complex.workflow2.yaml
  - 02-configmap_02-complex.workflow2-resources.yaml
  - 03-configmap_complex.workflow2-props.yaml

namespace: sonataflow-infra

configurations:
- config/image-configuration.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - envs:
      - secret.properties
    name: complex.workflow2-secret
configMapGenerator:
  - envs:
      - config.properties
    name: complex.workflow2-gitops

# Replace dev profile in SonataFlow instance(s), add image and envFrom
patches:
- path: sonataflow-patch.yaml
  target:
    kind: SonataFlow
    name: complex.workflow2
images:
- name: serverless-workflow-complex.workflow2
  newName: quay.io/gfarache/complex-workflow
  newTag: 8ad9e254d7f09aaf0b4ee44ee5af196f3e3e8512
